AptechSem3FinalProject/Web/Areas/Instructors/Models/ModuleViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Areas.Instructors.Models
{
    public class ModuleItemViewModel
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public byte Status { get; set; }
        public List<LessonItemViewModel> LessonItemViewModels { get; set; }
    }

    public class CreateModuleViewModel
    {
        [Required]
        public int CourseId { get; set; }
        [Required]
        public string Name { get; set; }
    }

    public class EditModuleViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

AptechSem3FinalProject/Web/Areas/Instructors/Controllers/ModuleController.cs
using AutoMapper;
using Context.Database;
using Model.Enum;
using Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Areas.Instructors.Models;

namespace Web.Areas.Instructors.Controllers
{
    [Helper.Sercurity.Authorize(RoleEnum.Author)]
    public class ModuleController : Controller
    {
        private readonly IUserService userService;
        private readonly ILectureService lectureService;
        private readonly ICourseService courseService;
        private readonly IVideoService videoService; 

        public ModuleController(IUserService userService, ILectureService lectureService, ICourseService courseService, IVideoService videoService)
        {
            this.userService = userService;
            this.lectureService = lectureService;
            this.courseService = courseService;
            this.videoService = videoService;
        }
        // GET: Instructors/Module
        [Helper.Sercurity.Authorize(RoleEnum.Author)]
        public ActionResult Index()
        {
            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        // GET: Instructors/Module/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // POST: Instructors/Module/Create
        [Helper.Sercurity.Authorize(RoleEnum.Author)]
        [HttpPost]
        public ActionResult Create(CreateModuleViewModel formData)
        {
            var loggedUser = Helper.Sercurity.SessionPersister.AccountInformation.UserId;
            if (!ModelState.IsValid)
            {
                new HttpStatusCodeResult(HttpStatusCode.NotAcceptable);
            }

            var course = courseService.GetById(formData.CourseId);
            if (course == null || course.UserId != loggedUser)
            {
                new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            var moduleToBeSaved = new Lecture
            {
                Name = formData.Name,
                Status = (byte)1,
                CourseId = formData.CourseId
            };
            var savedModule = lectureService.Add(moduleToBeSaved);
            return Content(Helper.RenderHelper.RenderViewToString( ControllerContext, "Create", Mapper.Map<ModuleItemViewModel>(savedModule)));
        }

        // POST: Instructors/Module/Edit/5
        [Helper.Sercurity.Authorize(RoleEnum.Author)]
        [HttpPost]
        public ActionResult Edit(EditModuleViewModel formData)
        {
            var loggedUser = Helper.Sercurity.SessionPersister.AccountInformation.UserId;
            if (!lectureService.IsEditable(loggedUser, formData.Id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            if (!ModelState.IsValid)
            {
                new HttpStatusCodeResult(HttpStatusCode.NotAcceptable);
            }
            var moduleToBeUpdated = lectureService.Get(formData.Id);
            moduleToBeUpdated.Name = formData.Name;
            lectureService.Update(moduleToBeUpdated);
            return Json(Newtonsoft.Json.JsonConvert.SerializeObject( Mapper.Map<ModuleItemViewModel>(lectureService.Get(formData.Id))));
        }

        [Helper.Sercurity.Authorize(RoleEnum.Author)]
        public ActionResult Delete(int id)
        {
            try
            {
                var loggedUser = Helper.Sercurity.SessionPersister.AccountInformation.UserId;
                if (!lectureService.IsEditable(loggedUser, id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
                }

                var module = lectureService.Get(id);
                var courseId = module.CourseId;
                foreach(var lesson in module.Videos.ToArray())
                {
                    videoService.Delete(lesson);
                }
                lectureService.Delete(module);

                if (!courseService.ValidatePublishState(courseId))
                {
                    var course = courseService.GetById(courseId);
                    course.Status = (byte)CourseStatus.CREATED;
                    courseService.Update(course);
                }
                return RedirectToAction("Details", "Course", new {id=module.CourseId});
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
    }
}

AptechSem3FinalProject/Web/Areas/Instructors/Views/Module/Create.cshtml
@model Web.Areas.Instructors.Models.ModuleItemViewModel

<div class="box box-info" id="module_@Model.Id">
    <div class="box-header with-border">
        <h3 class="box-title">@Model.Name</h3>
        <h3 class="box-title">
            <button type="button" class="btn btn-box-tool edit-module-title" data-id="@Model.Id" data-title="@Model.Name">
                <i class="fa fa-edit fa-2x"></i>
            </button>
        </h3>
        <h3 class="box-title">
            <a onclick="return confirm('Are you sure?')" href="@Url.Action("Delete", "Module", new { Model.Id})" class="btn btn-box-tool delete-module" data-id="@Model.Id">
                <i class="fa fa-trash fa-2x"></i>
            </a>
        </h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="table-responsive">
            @if (Model.LessonItemViewModels.Count >= 0)
            {
                <table class="table no-margin">
                    <thead>
                        <tr>
                            <th>Lesson title</th>
                            <th>Creation date</th>
                            <th>Is Preview</th>
                            <th>Disable</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var lesson in Model.LessonItemViewModels)
                        {
                            @Html.Partial("../Lesson/Create", lesson)
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div>No lesson found</div>
            }
        </div>
    </div>

    <div class="box-footer clearfix">
        <button type="button" class="btn btn-default add-lesson-modal" data-toggle="modal" data-target="#add-lesson-modal" data-backdrop="static" data-keyboard="true" data-module-id="@Model.Id">Create new lesson</button>
    </div>
</div>

AptechSem3FinalProject/Web/Areas/Instructors/Views/Module/Details.cshtml
@model Web.Areas.Instructors.Models.AuthorModuleViewModels
@{ 
    var categories = ViewBag.Category;
}
<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Latest Orders</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="table-responsive">
                <table class="table no-margin">
                    <thead>
                        <tr>
                            <th>Order ID</th>
                            <th>Item</th>
                            <th>Status</th>
                            <th>Popularity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR9842</a></td>
                            <td>Call of Duty IV</td>
                            <td><span class="label label-success">Shipped</span></td>
                            <td>
                                <div class="sparkbar" data-color="#00a65a" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR1848</a></td>
                            <td>Samsung Smart TV</td>
                            <td><span class="label label-warning">Pending</span></td>
                            <td>
                                <div class="sparkbar" data-color="#f39c12" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR7429</a></td>
                            <td>iPhone 6 Plus</td>
                            <td><span class="label label-danger">Delivered</span></td>
                            <td>
                                <div class="sparkbar" data-color="#f56954" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR7429</a></td>
                            <td>Samsung Smart TV</td>
                            <td><span class="label label-info">Processing</span></td>
                            <td>
                                <div class="sparkbar" data-color="#00c0ef" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR1848</a></td>
                            <td>Samsung Smart TV</td>
                            <td><span class="label label-warning">Pending</span></td>
                            <td>
                                <div class="sparkbar" data-color="#f39c12" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR7429</a></td>
                            <td>iPhone 6 Plus</td>
                            <td><span class="label label-danger">Delivered</span></td>
                            <td>
                                <div class="sparkbar" data-color="#f56954" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                        <tr>
                            <td><a href="pages/examples/invoice.html">OR9842</a></td>
                            <td>Call of Duty IV</td>
                            <td><span class="label label-success">Shipped</span></td>
                            <td>
                                <div class="sparkbar" data-color="#00a65a" data-height="20"><canvas width="34" height="20" style="display: inline-block; width: 34px; height: 20px; vertical-align: top;"></canvas></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#add-lesson-modal" data-backdrop="static" data-keyboard="true">
                Create new lesson
            </button>
            <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
        </div>
        <!-- /.box-footer -->
    </div>

</section>