AptechSem3FinalProject/Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using System.Web.UI;
using AutoMapper;
using Context.Database;
using Model.Enum;
using Service.Service;
using Web.Models;


namespace Web.Controllers
{
    public class CourseController : Controller
    {
        #region Declare field and Constructors

        private ICourseService _courseService;
        private IUserService _userService;
        private ILectureService _lectureService;
        private IVideoService _videoService;
        private IOrderService _orderService;
        private ICommentService _commentService;
        private ICategoryService _categoryService;

        public CourseController(ICourseService courseService, IUserService userService, ILectureService lectureService, IVideoService videoService, IOrderService orderService, ICommentService commentService, ICategoryService categoryService)
        {
            _courseService = courseService;
            _userService = userService;
            _lectureService = lectureService;
            _videoService = videoService;
            _orderService = orderService;
            _commentService = commentService;
            _categoryService = categoryService;
        }

        #endregion

        #region Action methods

        // GET: Course
        public ActionResult Index()
        {
            var showCoursesViewModel = new ShowCoursesViewModel();
            var popularCourses = _courseService.GetPublished().Take(4);
            var lastedCourses = _courseService.GetLastedCourse();
            showCoursesViewModel.PopularCourses = Mapper.Map<List<CourseItemViewModel>>(popularCourses);
            showCoursesViewModel.LastedCourses = Mapper.Map<List<CourseItemViewModel>>(lastedCourses);

            ViewBag.Category = _categoryService.GetAll();
            return View(showCoursesViewModel);
        }

        public ActionResult CourseDetail(int id)
        {
            var courseDetailViewModel = new CourseDetailViewModel();
            var course = _courseService.GetById(id);
            courseDetailViewModel.CourseListItemViewModel = Mapper.Map<CourseItemViewModel>(course);
            courseDetailViewModel.Author = _userService.GetById(course.UserId);
            courseDetailViewModel.CourseOutline = Mapper.Map<List<CourseOutlineViewModel>>(_lectureService.GetByCourseId(course.Id));
            courseDetailViewModel.RelatedCourses = Mapper.Map<List<CourseItemViewModel>>(course.Category.Courses
                    .OrderByDescending(relCourse => relCourse.Id).Take(5));
            if (Helper.Sercurity.SessionPersister.AccountInformation != null)
            {
                var loggedUserId = Helper.Sercurity.SessionPersister.AccountInformation.UserId;
                courseDetailViewModel.IsPaid = _courseService.ValidateCourseAccessible(loggedUserId, id);
            }
            return View(courseDetailViewModel);
        }

        [Helper.Sercurity.Authorize]
        public ActionResult CoursePlay(int id, int? video)
        {
            var loggedUserId = Helper.Sercurity.SessionPersister.AccountInformation.UserId;
            if (_courseService.ValidateCourseAccessible(loggedUserId, id))
            {
                var course = _courseService.GetById(id);
                if(course.Status == (byte)CourseStatus.DELETED)
                {
                    return RedirectToAction("Errors", "NotFound");
                }
                if (!_orderService.GetOrderByCourseAndUser(course.Id, loggedUserId).Any() && course.UserId != loggedUserId)
                {
                    _orderService.AddOrder(course, loggedUserId, (int)(PaymentType.FREE));
                }

                var coursePlayViewModel = new CoursePlayViewModel
                {
                    CourseModuleViewModels = new List<CourseModuleViewModel>(),
                    CourseItemViewModel = Mapper.Map<CourseItemViewModel>(course)
                };
                foreach (var lecture in course.Lectures)
                {
                    var lectureMap = new CourseModuleViewModel
                    {
                        CourseLessonViewModels = Mapper.Map<List<CourseLessonViewModel>>(lecture.Videos),
                        Id = lecture.Id,
                        Name = lecture.Name
                    };
                    coursePlayViewModel.CourseModuleViewModels.Add(lectureMap);
                }

                coursePlayViewModel.CurrentLesson = video != null ? Mapper.Map<CourseLessonViewModel>(_videoService.GetById(video)) : coursePlayViewModel.CourseModuleViewModels.First().CourseLessonViewModels.First();
                return View(coursePlayViewModel);
            } else
            {
                return RedirectToAction("PaymentWithPaypal", "Payment", new { id = id });
            }

        }
        #endregion

        #region manipulate methods



        #endregion

        public string LoadMore(int offset)
        {
            var showCoursesViewModel = new LoadMoreCourseViewModel();
            var courses = _courseService.GetPublished().Skip(offset).Take(10);
            showCoursesViewModel.CourseItemViewModels = Mapper.Map<List<CourseItemViewModel>>(courses);
            return Helper.RenderHelper.RenderViewToString(ControllerContext, "LoadMore", showCoursesViewModel);
        }

        [HttpPost]
        public ActionResult Search(FormCollection formData)
        {
            IEnumerable<Course> createdCourses = new List<Course>();
            int cateId = 0;
            Int32.TryParse(Convert.ToString(formData["category"]), out cateId);
            string courseTitle = Convert.ToString(formData["title"]);
            if (cateId != 0)
            {
                createdCourses = _courseService.GetAll(course => course.Title.Contains(courseTitle) && course.CategoryId == cateId);
            }
            else
            {
                createdCourses = _courseService.GetAll(course => course.Title.Contains(courseTitle));
            }
            var returnModel = Mapper.Map<List<CourseItemViewModel>>(createdCourses);
            return Content(Helper.RenderHelper.RenderViewToString(ControllerContext, "~/Views/Course/Search.cshtml", returnModel));
        }
    }
}

AptechSem3FinalProject/Web/Controllers/InstructorController.cs
using AutoMapper;
using Model.Enum;
using Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class InstructorController : Controller
    {       
        private readonly IAccountService _accountService;
        private readonly IUserService _userService;

        public InstructorController(IAccountService accountService, IUserService userService)
        {
            this._accountService = accountService;
            this._userService = userService;
        }

        // GET: Instructor
        [Helper.Sercurity.Authorize]
        public ActionResult Index()
        {
            ApplyAuthorViewModel applyAuthorViewModel = new ApplyAuthorViewModel();
            var user = _userService.GetById(Helper.Sercurity.SessionPersister.AccountInformation.UserId);
            applyAuthorViewModel = Mapper.Map<ApplyAuthorViewModel>(user);
            return View(applyAuthorViewModel);
        }

        [HttpPost]
        public ActionResult Apply(ApplyAuthorViewModel formData)
        {
            if (ModelState.IsValid)
            {
                var loggedAccount = Helper.Sercurity.SessionPersister.AccountInformation;
                var loggedUser = _userService.GetById(loggedAccount.UserId);
                loggedUser.Company = formData.Company;
                loggedAccount.RoleId = (int)RoleEnum.Author;
                _userService.Update(loggedUser);
                _accountService.Update(loggedAccount);
                return RedirectToAction("Index", "Dashboard", new { area= "Instructors" }); ;
            }
            return View("index", formData);
        }
    }
}

AptechSem3FinalProject/Web/Controllers/UserController.cs
using Model.Enum;
using Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IOrderService orderService;

        public UserController(IUserService userService, IOrderService orderService)
        {
            this.userService = userService;
            this.orderService = orderService;
        }

        // GET: User
        [Helper.Sercurity.Authorize(RoleEnum.User, RoleEnum.Author)]
        public ActionResult Index()
        {
            var loggedUser = Helper.Sercurity.SessionPersister.AccountInformation.UserId;

            return View(orderService.GetByUser(loggedUser));
        }

        // GET: User/Details/5
        [Helper.Sercurity.Authorize(RoleEnum.User, RoleEnum.Author)]
        public ActionResult Details()
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AptechSem3FinalProject/Web/Views/Shared/_Footer.cshtml
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-6 col-sm-12">
                <div class="single-footer-widget">
                    <h4>Top Products</h4>
                    <ul>
                        <li><a href="#">Managed Website</a></li>
                        <li><a href="#">Manage Reputation</a></li>
                        <li><a href="#">Power Tools</a></li>
                        <li><a href="#">Marketing Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-12">
                <div class="single-footer-widget">
                    <h4>Quick links</h4>
                    <ul>
                        <li><a href="#">Jobs</a></li>
                        <li><a href="#">Brand Assets</a></li>
                        <li><a href="#">Investor Relations</a></li>
                        <li><a href="#">Terms of Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-12">
                <div class="single-footer-widget">
                    <h4>Features</h4>
                    <ul>
                        <li><a href="#">Jobs</a></li>
                        <li><a href="#">Brand Assets</a></li>
                        <li><a href="#">Investor Relations</a></li>
                        <li><a href="#">Terms of Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-12">
                <div class="single-footer-widget">
                    <h4>Resources</h4>
                    <ul>
                        <li><a href="#">Guides</a></li>
                        <li><a href="#">Research</a></li>
                        <li><a href="#">Experts</a></li>
                        <li><a href="#">Agencies</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-12">
                <div class="single-footer-widget">
                    <h4>Newsletter</h4>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get">
                            <div class="input-group">
                                <input type="text" class="form-control" name="EMAIL" placeholder="Enter Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email Address '" required="" type="email">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="lnr lnr-arrow-right"></span>
                                    </button>
                                </div>
                                <div class="info"></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom row align-items-center justify-content-between">
            <p class="footer-text m-0 col-lg-6 col-md-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>

AptechSem3FinalProject/Web/Views/Shared/_Header.cshtml
@using Web.Areas.Instructor
@using Model.Enum;
@using AuthenticationManager = Web.Helper.Sercurity.AuthenticationManager
<header id="header" class="header-scrolled">
    @using (Html.BeginForm("Logout", "Account", FormMethod.Post, new {id = "userLogoutForm"}))
    {
        @Html.AntiForgeryToken()
    }
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="@Url.Action("index", "Home")">
                    <img src="@Url.Content("~/img/logo.png")" alt="" title=""/>
                </a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li>@Html.ActionLink("Home", "index", "Home")</li>
                    <li>
                        <a href="@Url.Action("Index", "Course")">Courses</a>
                    </li>                    
                    @*<li class="menu-has-children">
                        <a href="">Categories</a>
                        <ul>
                            <li><a href="blog-home.html">Blog Home</a></li>
                            <li><a href="blog-single.html">Blog Single</a></li>
                        </ul>
                    </li>*@
                    @{
                        ViewBag.Title = "Contact";
                        if (!AuthenticationManager.IsAuthenticated)
                        {
                            <li>
                                <a href="@Url.Action("Login", "Account")">Login</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Register", "Account")" class="user-logout-link">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="menu-has-children">
                                <a href="#">Account</a>
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Index", "User")">Billing History</a>
                                    </li>
                                    <li>
                                        <div class="clearfix"></div>
                                    </li>
                                    <li>
                                        @if (!AuthenticationManager.Is(RoleEnum.Author))
                                        {
                                            <a href="@Url.Action("Index","Instructor")">Become an instructor</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Index", "Dashboard", new {area="Instructors"})">Instructor dashboard</a>
                                        }
                                    </li>
                                    <li>
                                        <a href="@Url.Action("ResetPassword","Account")">Change password</a>
                                    </li>
                                    <li>
                                        
                                        <a href="@Url.Action("Logout", "Account")" id="userLogoutLink">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    }                   
                </ul>
            </nav>
        </div>
    </div>
</header>

AptechSem3FinalProject/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="@Url.Content("~/img/fav.png")">
    <meta name="author" content="colorlib">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    @Styles.Render("~/Content/css")
</head>
<body>

    @RenderPage("_Header.cshtml")

    @RenderBody()

    @RenderPage("_Footer.cshtml")

    <script src="~/Scripts/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/js/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/js/easing.min.js"></script>
    <script src="~/Scripts/js/hoverIntent.js"></script>
    <script src="~/Scripts/js/superfish.min.js"></script>
    <script src="~/Scripts/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/Scripts/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/js/jquery.tabs.min.js"></script>
    <script src="~/Scripts/js/jquery.nice-select.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/mail-script.js"></script>
    <script src="~/Scripts/plyr/dist/plyr.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/video-hander.js"></script>
    <script src="~/Scripts/js/simplebar.min.js"></script>
    <script src="~/Scripts/Client/Client.js"></script>
    @RenderSection(@"Scripts", false)
</body>
</html>